export const Locators = {
    searchForMearchantInput: '[data-testid="search-for-a-merchant"]',
    jetBlueCard: '[href="/jetblue"]',
    setAmountInput: '#field-8',
    emailInput: '#2-email',
    passwordInput: '[aria-label="Password"]',
    signUpButton: '#2-submit',
    setSavingsAmountInput: '[data-testid="savings-goal-amount-input"]',
    dashboardBanner: '[data-testid="banner-title"]',
    firstNameInput: "#firstName",
    lastNameInput: "#lastName",
    phoneInput: '[data-testid="phone-input"]',
    setUpNowButton: '[href="/kyc?type=savings-plan"]',
    savingsAmountInput: '[data-testid="input-currency-amount"]',
    continueBtn: '[data-testid="amount-save-button"]',
    addressInput: '#address',
    stateInput: '#state',
    zipCodeInput: '#zipCode',
    cityInput: '#usersCity',
    dobInput: '#dob',
    ssnInput: '#ssn',
    checkbox: 'input[type="checkbox"]',
    submitButton: '[type="submit"]',
    stateNYoption: '[value="NY"]',
    searchInstitutionInput: '[placeholder="Search"]',
    userId: '#aut-input-0',
    userPass: 'aut-input-1'
}